export { workspaceMemberRoutes } from '@workspaceModules/members/workspaceMemberRoutes'
export { workspacePlaylistContentManagerRoutes } from '@workspaceModules/playlistContentManager/workspacePlaylistContentManagerRoutes'
export { workspacePlaylistLayoutEditorRoutes } from '@workspaceModules/playlistLayoutEditor/workspacePlaylistLayoutRoutes'
export { workspaceFileRoutes } from '@workspaceModules/file/workspaceFileRoutes'
export { workspacePlaylistLayoutRoutes } from '@workspaceModules/playlistLayout/workspacePlaylistLayoutRoutes'
export { workspacePlaylistRoutes } from '@workspaceModules/playlist/workspacePlaylistRoutes'
export { workspaceScreenRoutes } from '@workspaceModules/screen/workspaceScreenRoutes'