FROM node:lts-alpine3.17

WORKDIR /app

RUN apk add --no-cache ffmpeg

COPY package*.json ./
COPY prisma ./prisma
RUN npm install
RUN npx prisma generate

COPY . .

EXPOSE 3000

CMD npm run db:deploy && npm run dev