FROM node:lts

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg && apt-get clean

COPY package*.json ./
COPY prisma ./prisma
RUN npm install

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "npm run db:deploy && npm run dev"]