export enum AdminPermissionName {
    SETTINGS = 'settings',
    USERS_VIEW = 'users.view',
    USERS_EDIT = 'users.edit',
    USERS_DELETE = 'users.delete',
    USERS_MANAGE_ADMIN_PERMISSIONS = 'users.manage-admin-permissions',
    USERS_DISABLE_TWO_FACTOR_AUTH = 'users.disable-two-factor-auth',
    SESSIONS_VIEW = 'sessions.view',
    WORKSPACES_CREATE = 'workspaces.create',
    WORKSPACES_SOFT_DELETE = 'workspaces.soft-delete',
    WORKSPACES_DELETE = 'workspaces.delete',
    WORKSPACES_VIEW = 'workspaces.view',
    WORKSPACES_UPDATE = 'workspaces.update',
    WORKSPACE_INVITATIONS_VIEW = 'workspace-invitations.view',
    WORKSPACE_INVITATIONS_CREATE = 'workspace-invitations.create',
    WORKSPACE_INVITATIONS_CANCEL = 'workspace-invitations.cancel',
    WORKSPACE_MEMBERS_VIEW = 'workspace-members.view',
}